"""Stable public facade for orchestration and runtime integration."""

from __future__ import annotations

from typing import Protocol

from sage.memory.models import (
    ContextExpansionRequest,
    ContextForest,
    DirectMaterializationRequest,
    MemoryMode,
    MemoryRunReport,
    MemoryRunRequest,
    MutationAuthorization,
    SourceReadEvent,
)


class MemorySession(Protocol):
    @property
    def mode(self) -> MemoryMode: ...
    async def initial_context(self, issue_text: str) -> ContextForest: ...
    async def expand(self, request: ContextExpansionRequest) -> ContextForest: ...
    async def materialize_dependency(
        self, request: DirectMaterializationRequest
    ) -> str: ...
    async def list_tree(self, *, path: str, max_depth: int) -> str: ...
    async def search_text(
        self, *, query: str, path: str, max_results: int
    ) -> str: ...
    async def read_file(
        self, *, path: str, start_line: int, end_line: int | None
    ) -> str: ...
    def inspect_context(self) -> str: ...
    def record_read(self, event: SourceReadEvent) -> None: ...
    def authorize_mutation(self, request: MutationAuthorization) -> None: ...
    def record_mutation(self, *paths: str) -> None: ...
    async def finalize(self, outcome: object) -> MemoryRunReport: ...


class MemoryEngine(Protocol):
    async def begin(self, request: MemoryRunRequest) -> MemorySession: ...
    async def close(self) -> None: ...
